name: Deploy Production v1

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      ############################################
      # 1. récupérer IP runner GitHub
      ############################################
      - name: Get runner IP
        id: ip
        uses: haythem/public-ip@v1.3

      ############################################
      # 2. whitelist IP via cPanel API
      ############################################
      - name: Whitelist IP cPanel
        run: |
          curl -s \
            -H "Authorization: cpanel ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_API_TOKEN }}" \
            "https://${{ secrets.CPANEL_SERVER }}:2083/execute/SshWhitelist/add?address=${{ steps.ip.outputs.ipv4 }}&port=22"

      ############################################
      # 3. deploy SSH
      ############################################
      - name: Execute deployment on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd noahbuisson.fr/wp-content/themes/noahbuisson

            git fetch origin
            git reset --hard origin/main
            git clean -fd

            npm ci
            npm run build:prod

      ############################################
      # 4. cleanup whitelist (sécurité)
      ############################################
      - name: Remove whitelist (always)
        if: always()
        run: |
          curl -s \
            -H "Authorization: cpanel ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_API_TOKEN }}" \
            "https://${{ secrets.CPANEL_SERVER }}:2083/execute/SshWhitelist/remove_all"